#!/usr/bin/env bash

wallpaper="$HOME/Pictures/Wallpapers/catppuccin/triangle.jpg"

# Show menu options
if [ -z "$@" ]; then
  echo "  Lock"
  echo "󰍃  Logout"
  echo "󰜉  Reboot"
  echo "  Shutdown"
  exit 0
fi

# Match selected option
case "$1" in
  "  Lock")
    exec swaylock 
    ;;
  "󰍃  Logout")
    swaynag \
      -t warning \
      -m "You pressed the exit shortcut. Do you really want to exit Sway? This will end your Wayland session." \
      -B "Yes, exit Sway" "swaymsg exit"
    ;;
  "󰜉  Reboot")
    exec systemctl reboot
    ;;
  "  Shutdown")
    exec systemctl poweroff
    ;;
esac
